version: '3.3'

services:
  # Busstop
  Busstop:
    container_name: "Busstop"
    build:
      context: ./busStop
      dockerfile: Dockerfile
    ports:
      - 6030:6030
    deploy:
      restart_policy:
        condition: on-failure
    image: jiameelorh/eti-quiz

networks:
  default: null
volumes:
  ridesharevol: null